config/routes.rb
Rails.application.routes.draw do
  resources :attachments, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :download
      post :generate_public_link, to: "public_link#generate_public_link"
    end
  end

  get "/tiny/:key", to: "public_link#show", as: :public_link

  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "attachments#index"
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :user
  has_many :public_links, dependent: :destroy

  def key
    public_links.valid_links.order(expire_at: :desc).first&.key
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  include AttachmentConcern
  include AttachmentsHelper

  before_action :set_attachment, only: %i[ show destroy download ]

  # GET /attachments or /attachments.json
  def index
    @attachments = Attachment.where(user: @user)
  end

  # GET /attachments/1 or /attachments/1.json
  def show
    if @attachment&.user == @user
      render action: :show, layout: false
    else
      render plain: "You are not authorized to access this attachment.", status: :unauthorized
    end
  end

  def download
    if @attachment&.user == @user
      result = download_attachment
      if result[:success]
        render :show, status: result[:status], notice: result[:message]
      else
        render plain: result[:message], status: result[:status]
      end
    else
      render plain: "You are not authorized to access this attachment.", status: :unauthorized
    end
  end
  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # POST /attachments or /attachments.json
  def create
    @attachment = new_attachment

    if (uploaded_file = attachment_params[:file].presence)
      if @attachment.save
        File.open(file_path, "wb") do |file|
          file.write(uploaded_file.read)
        end

        redirect_to attachments_path, notice: "Attachment was successfully created." and return
      end
    else
      @attachment.errors.add(:file, "can't be blank")
    end
    render :new, status: 422
  end

  def destroy
    FileUtils.rm(file_path) if File.exist?(file_path)
    @attachment.destroy!
    redirect_to attachments_path, status: :see_other, notice: "Attachment was successfully destroyed."
  end

  private

  # Only allow a list of trusted parameters through.
  def attachment_params
    params.fetch(:attachment, {}).permit(:title, :description, :file)
  end

  def new_attachment
    _attachment_params = attachment_params
    Attachment.new(
      title: _attachment_params[:title],
      description: _attachment_params[:description],
      file_name: _attachment_params[:file].original_filename,
      user: @user
    )
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
  ROOT_PATH = Rails.root.join("public", "uploads")
  def download_attachment
    if File.exist?(file_path)
      send_file file_path, filename: @attachment.file_name, type: "application/octet-stream", disposition: "attachment"
      {success: true, message: "File downloaded successfully", status: 200}
    else
      {success: false, message: "File not found", status: 404}
    end
  end

  private
  def file_path
    dir = ROOT_PATH.join(@user.id.to_s)
    FileUtils.mkdir_p(dir) unless File.exist?(dir)

    dir.join(@attachment.id.to_s + "_" + @attachment.file_name)
  end
end

app/views/attachments/_attachment.html.erb
<div id="<%= dom_id attachment %>">
  <h2><%= attachment.title %></h2>
  <div>
    <b>Description</b>: <%= attachment.description %>
  </div>
</div>

app/views/attachments/_form.html.erb
<%= form_with(model: attachment) do |form| %>
  <% if attachment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div  class="field">
    <%= form.label :description %>
    <%= form.text_area :description, required: false %>
  </div>

  <div class="field">
    <%= form.label :file, 'Upload your file' %>
    <%= form.file_field :file, required: true %>
  </div>

  <div class="actions">
    <%= form.submit 'Upload Document' %>
  </div>
<% end %>

app/views/attachments/index.html.erb
<% if Current.user %>
  <div>
    <%= button_to "Logout", session_path, method: :delete %>
  </div>
<% end %>
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<% content_for :title, "Attachments" %>

<h1>Attachments</h1>

<div id="attachments">
  <table>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Action</th>
    </tr>
    
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.id %></td>
        <td><%= attachment.title %></td>
        <td><%= link_to "Show this attachment", attachment %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New attachment", new_attachment_path %>

app/views/attachments/new.html.erb
<% content_for :title, "New attachment" %>

<h1>New attachment</h1>
<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Back to attachments", attachments_path %>
</div>

app/views/attachments/show.html.erb
<p style="color: green">
<!--  Fix notice when attachment is downloaded-->
  <%= notice %>
</p>

<div>
  <%= link_to "Back to attachments", attachments_path %>
  <%= render @attachment %>

  <%= link_to "Download attachment", download_attachment_path %>
  <%= button_to "Destroy this attachment", @attachment, method: :delete %>
  <%= form_with url: generate_public_link_attachment_path(@attachment), method: :post, remote: true do |form| %>
    <%= form.submit "Generate Public URL" %>
  <% end %>

</div>

<div>
  <% if @attachment.key %>
    Public Link: <%= public_link_url @attachment.key %>
  <% end %>
</div>

<div id="public-url-container"></div>